# Generated by Django 3.1.4 on 2021-07-31 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('likes', models.TextField(blank=True, null=True)),
                ('views', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='posts', verbose_name='Photo')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
